homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret lng
  elevation: 129
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml

panel_iframe:
#  cctv:
#    title: 'CCTV'
#    icon: mdi:cctv
#    url: 'http://cascadehome.net:8181/login.htm'

# Show links to resources in log and frontend
# introduction:

frontend:
#  extra_html_url:
#    - /local/custom_ui/state-card-floorplan.html

# Enables configuration UI
config:

http:
  base_url: !secret base_url
  api_password: !secret api_password

api:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# Plex player
media_player:
  - platform: plex

# Alerts
alert:
  garage_door:
    name: Garage is open
    done_message: Garage is closed
    entity_id: sensor.garage_door
    state: 'Open'
    repeat: 30
    can_acknowledge: True
    skip_first: True
    notifiers:
      - slack

# View all events in a logbook
logbook:
  exclude:
    entities:
      - group.internalpir
      - group.groundfloorpir
      - group.firstfloorpir
      - group.externalpir
      - group.reedswitches
      - light.kitchen_led_left
      - light.kitchen_led_right
      - sensor.lastfm_dazrave
      - sensor.steam_76561198131186539
      - sensor.met_office_weather
      - sensor.yr_symbol
      - sensor.met_office_wind_direction
      - sensor.met_office_wind_gust
      - sensor.met_office_wind_speed
      - sensor.met_office_visibility
      - sensor.met_office_visibility_distance
      - sensor.met_office_feels_like_temperature
      - sensor.met_office_humidity
      - binary_sensor.workday_sensor
    domains:
      - automation
      - binary_sensor
      - media_player

# Enables a map showing the location of tracked devices
map:

#cast:
#  media_player:
#  - host: 192.168.0.40

# Track the sun
sun:

#joaoapps_join:
#  - name: darren_oneplus
#    device_id: group.android
#    api_key: !secret join_api_darren
#  - name: stephanie_sony
#    device_id: group.android
#    api_key: <api_key2>

# shopping_list:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

alarm_control_panel:
  - platform: manual
    name: "Home Alarm"
    # code: !secret alarm_code
    pending_time: 25
    trigger_time: 25
    disarm_after_trigger: false

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#bmw_connected_drive:
#  name:
#    username: !secret bmw_username
#    password: !secret bmw_password
#    region: "rest_of_world"

# Types
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
script: !include scripts.yaml
zone: !include zones.yaml

# Configurations
cloud: !include configuration/cloud.yaml
sensor: !include configuration/sensors.yaml
input_boolean: !include configuration/input_boolean.yaml
binary_sensor: !include configuration/binary_sensors.yaml
light: !include configuration/lights.yaml
camera: !include configuration/cameras.yaml
switch: !include configuration/switch.yaml
notify: !include configuration/notify.yaml

# Device list
nest: !include devices/nest.yaml
device_tracker: !include devices/tracker.yaml

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  password: !secret mqtt
