title: Cascade Home
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
views:
    # View tab title.
  - icon: mdi:home-assistant
    title: Overview
    id: home
    background: grey
    theme: dark-mode
    cards:
    # Left stack
    - type: vertical-stack
      cards:
        - type: entity-filter
          show_empty: false
          entities:
            - group.darren
            - group.stephanie
            - alarm_control_panel.home_alarm
          state_filter:
            - "home"
            - "armed_away"
            - "armed_home"
            - "triggered"
            - "pending"
            - "on"
        - type: entities
          entities:
            - sensor.last_activity
        - type: entities
          title: Lights
          show_header_toggle: false
          entities:
            - entity: light.kitchen_counter
              name: Kitchen Counter
            - entity: light.living_room_lamp
              name: Living Room Lamp
            - entity: light.garden_flood_light
              name: Garden Floodlight
              icon: mdi:track-light
            - entity: switch.general_1
              name: Fan Heater
              icon: mdi:radiator
            #- entity: light.office_desk_led
            #  name: Office Desk
            #  icon: mdi:desk-lamp

    #    - type: glance
    #      entities:
    #        - sensor.bins

    # Right stack
    - type: vertical-stack
      cards:
        - type: thermostat
          entity: climate.hallway
        #- type: entities
        #  title: Climate
        #  entities:
        #    - entity: climate.hallway
        #      name: Thermostat
        #    - entity: sensor.met_office_temperature
        #      name: Outside
        #    - entity: sensor.met_office_probability_of_precipitation
        #      name: Rain Chance

    # View tab title.
  - icon: mdi:cctv
    title: CCTV
    id: cctv
    background: grey
    theme: dark-mode
    cards:
    # row 1
    - type: horizontal-stack
      cards:
        - type: entities
          title: Security
          show_header_toggle: false
          entities:
            - alarm_control_panel.home_alarm
            - sensor.last_activity
            - automation.turn_on_alarm_when_away
            - automation.turn_on_alarm_when_sleeping_on_weekday
            - switch.alarm_siren
            #- binary_sensor.back_room
            #- binary_sensor.kitchen
            #- binary_sensor.landing
            #- binary_sensor.living_room
    # row 2
    - type: horizontal-stack
      cards:
        - type: picture-glance
          title: Garage
          entities:
            - switch.garage_door_up
            - sensor.garage_door
            - switch.garage_door_down
          camera_image: camera.garage
        - type: picture-glance
          title: Front
          entities:
            - camera.front_garden
          camera_image: camera.front_garden

    # View tab title.
  - icon: mdi:account-group
    title: Residents
    id: residents
    background: grey
    theme: dark-mode
    cards:
    # Left stack
    - type: horizontal-stack
      cards:
        - type: entities
          entities:
            - group.darren # Darren
            - group.stephanie # Stephanie
            - input_boolean.dog_mode
            - input_boolean.guest_mode





    # Right stack
    - type: vertical-stack
      cards:
        - type: map
          aspect_ratio: 100%
          entities:
            - entity: zone.home
            - device_tracker.google_maps_109369459484370838012 # Darren
            - device_tracker.google_maps_112615938731075593608 # Stephanie
            - zone.protective_packaging
            - zone.tickx

    - type: horizontal-stack
      cards:
        - type: entities
          entities:
            - sensor.lastfm_dazrave
            - sensor.steam_76561198131186539

    # View tab title.
  - icon: mdi:settings
    title: Settings
    id: settings
    background: grey
    theme: dark-mode
    cards:
    # Left stack
    - type: vertical-stack
      cards:
        - type: entities
          title: Network
          entities:
            - sensor.cascade_network_status
            - sensor.cascade_network_local_ip
            - sensor.cascade_network_uptime
            - sensor.cascade_network_last_restart
            - entity: sensor.pihole_ads_blocked_today
              name: Ads blocked today
              icon: mdi:image-off
            - entity: sensor.pihole_ads_percentage_blocked_today
              name: Monitored change
              icon: mdi:image-search
            - entity: sensor.pihole_dns_unique_domains
              name: DNS hits today
              icon: mdi:server-network
    # Right stack
    - type: vertical-stack
      cards:
        - type: entities
          title: Automations
          entities:
            - automation.turn_off_floodlight_after_5_minutes
            - automation.turn_on_heater_weekday_morning
            - automation.turn_off_fan_heater_after_30_minutes




