# Alarm Control

# Alarm is being set...
- alias: 'Set alarm'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'pending'
      from: 'disarmed'
  action:
  # Anologue bleep needed here
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.5
  - service: switch.turn_on
    entity_id: switch.garage_door_down

# Alarm has been set
- alias: 'Alarm ON'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
      for:
        seconds: 2
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_home'
      for:
        seconds: 2
  action:
  # Anologue bleep needed here
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.8
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1

# Alarm has been switched off
- alias: 'Alarm OFF'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
  # Anologue bleep needed here
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.8
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1

# Turn on alarm if residents are away (Checks every 15 minutes)
- alias: 'Turn on alarm when away'
  trigger:
    - platform: time
      minutes: '/15'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.internalpir
        state: 'off'
        for:
          minutes: 30
      - condition: state
        entity_id: group.resdidents
        state: 'away'
        for:
          minutes: 30
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'disarmed'
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm

# Turn on alarm if residents are potentially sleeping (Checks after 30 minutes of no motion)
- alias: 'Turn on alarm when sleeping'
  trigger:
  # Office motion detection needed
    - platform: state
      entity_id: group.internalpir
      to: 'off'
      for:
        minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: sensor.last_activity
        state: 'landing_motion'
      - condition: state
        entity_id: group.living_room_tv
        state: 'not_home'
  action:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.home_alarm

# Turn off alarm when residents are home
- alias: 'Turn off alarm when home'
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'armed_away'
        for:
          minutes: 30
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
  # Anologue bleep needed here
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.8
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1