# Alarm Control

# Alarm is being set...
- alias: 'Set alarm'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'pending'
      from: 'disarmed'
  action:
  # Anologue bleep needed here
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.5
  - service: switch.turn_on
    entity_id: switch.garage_door_down

# Alarm has been set
- alias: 'Alarm ON'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
      for:
        seconds: 2
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_home'
      for:
        seconds: 2
  action:
  # Anologue bleep needed here
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.8
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1

# Alarm has been switched off
- alias: 'Alarm OFF'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
  # Anologue bleep needed here
  - service: switch.turn_off
    entity_id: switch.alarm_siren
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.4

# Turn on alarm if residents are away (Checks every 15 minutes)
- alias: 'Turn on alarm when away'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/15'
      seconds: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.internalpir
        state: 'off'
        for:
          minutes: 10
      - condition: state
        entity_id: group.residents
        state: 'not_home'
        for:
          minutes: 10
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'disarmed'
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm
  - service: notify.slack
    data:
      message: "Alarm is ON"

# Turn on alarm if residents are potentially sleeping (Weekday)
- alias: 'Turn on alarm when sleeping on weekday'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/15'
      seconds: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      # Office motion detector needed
      - condition: state
        entity_id: group.internalpir
        state: 'off'
        for:
          minutes: 30
      - condition: state
        entity_id: sensor.last_activity
        state: 'Landing Motion'
      #- condition: state
      #  entity_id: sensor.living_room_tv
      #  state: 'off'
      - condition: time
        after: '00:00:00'
        before: '06:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.home_alarm

# Turn off alarm if residents are potentially awake (Weekday)
- alias: 'Turn off alarm when sleeping on weekday'
  initial_state: 'on'
  trigger:
  # Office motion detection needed
    - platform: state
      entity_id: binary_sensor.landing
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: group.groundfloorpir
        state: 'off'
        for:
          hours: 1
      #- condition: state
      #  entity_id: sensor.living_room_tv
      #  state: 'off'
      - condition: time
        after: '05:50:00'
        before: '08:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm

# Turn off alarm when residents are home
- alias: 'Turn off alarm when home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'armed_away'
        for:
          minutes: 5
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
  # Anologue bleep needed here
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 0.8
  - service: media_player.volume_set
    data_template:
      entity_id: group.speakers
      volume_level: 1
  - service: notify.slack
    data:
      message: "Alarm is OFF"


# Turn on alarm if residents are potentially sleeping (Weekend)
- alias: 'Turn on alarm when sleeping on weekend'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/15'
      seconds: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      # Office motion detector needed
      - condition: state
        entity_id: group.internalpir
        state: 'off'
        for:
          hours: 1
      - condition: state
        entity_id: sensor.last_activity
        state: 'Landing Motion'
      #- condition: state
      #  entity_id: sensor.living_room_tv
      #  state: 'off'
      - condition: time
        after: '01:00:00'
        before: '07:00:00'
        weekday:
          - fri
          - sat
  action:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.home_alarm

# Turn off alarm if residents are potentially awake (weekend)
- alias: 'Turn off alarm when sleeping on weekend'
  initial_state: 'on'
  trigger:
  # Office motion detection needed
    - platform: state
      entity_id: binary_sensor.landing
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: group.groundfloorpir
        state: 'off'
        for:
          hours: 1
      #- condition: state
      #  entity_id: sensor.living_room_tv
      #  state: 'off'
      - condition: time
        after: '07:00:00'
        before: '12:00:00'
        weekday:
          - sat
          - sun
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm

# Turn off siren after 30 minutes
- alias: 'Turn off siren'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.alarm_siren
      to: 'on'
      for:
        minutes: 30
  action:
  - service: switch.turn_off
    entity_id: switch.alarm_siren
