# Climate Control

# Turn on away_mode when away
- alias: 'Turn off heat with residents are away'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
  action:
  - service: climate.set_away_mode
    data:
      entity_id: climate.hallway
      away_mode: true

# Turn off away_mode when residents home
- alias: 'Turn off heat with residents are away'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
  - service: climate.set_away_mode
    data:
      entity_id: climate.hallway
      away_mode: false