# Garage Door control
- alias: 'Open garage door'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.garage_door_up
      to: 'on'
      for:
        seconds: 2
  action:
  - service: switch.turn_off
    entity_id: switch.garage_door_up

- alias: 'Close garage door'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.garage_door_down
      to: 'on'
      for:
        seconds: 2
  action:
  - service: switch.turn_off
    entity_id: switch.garage_door_down
