# Trigger if off
- alias: turn kitchen lights on if not already
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen
    to: 'on'
  condition:
    - condition: state
      entity_id: light.kitchen_counter
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_counter

- alias: Turn kitchen lights off after awhile
  trigger:
  - platform: state
    entity_id: light.kitchen_counter
    state: 'on'
    for:
      minutes: 30
  action:
  - service: light.turn_off
    entity_id: light.kitchen_counter
