- alias: Weekday Living Room Lamp off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.groundfloorpir
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '22:30:00'
      before: '06:00:00'
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: light.turn_off
      entity_id: light.living_room_lamp

- alias: Weekend Living Room Lamp off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.groundfloorpir
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '00:00:00'
      before: '08:00:00'
      weekday:
        - fri
        - sat
  action:
    - service: light.turn_off
      entity_id: light.living_room_lamp
