# Arming and disarming

- alias: 'Set alarm'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'pending'
      from: 'disarmed'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.all_speakers
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.all_speakers
    data_template:
      message: "Securing the home."
  - service: switch.turn_on
    entity_id: switch.garage_door_down

- alias: 'Alarm ON (home)'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_home'
  action:
  - service: tts.google_say
    entity_id: media_player.all_speakers
    data:
      message: "Alarm set"
  #- service: notify.slack
    #data_template:
      #message: ""
      #data:
        #attachments:
        #- color: >
        #  #c23b22
        #title: >
        #  The Alarm has been set
        #text: >
        #  *Mode:* {{states('alarm_control_panel.home_alarm')}}
        #author_name: >
        #  Security
        #author_icon: >
        #  http://res.cloudinary.com/dazrave/image/upload/b_rgb:00bdff,e_auto_color/v1515266273/DazRave%20Cascade/icons/security-home.png
        #attachment_type: >
        #  default
  #- service: light.turn_off
  #  entity_id: light.office_desk_led

- alias: 'Alarm Setup'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
      for:
        seconds: 2
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_home'
      for:
        seconds: 2
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.all_speakers
      volume_level: 1.0

- alias: 'Alarm OFF'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.all_speakers
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.all_speakers
    data:
      message: "Alarm deactivated."
  #- service: notify.slack
  #  data_template:
  #    message: ""
  #    data:
  #      attachments:
  #      - color: >
  #        #5e8c31
  #      title: >
  #        The Alarm has been deactivated
        #author_name: >
        #  Security
        #author_icon: >
        #  http://res.cloudinary.com/dazrave/image/upload/b_rgb:00bdff,e_auto_color/v1515266273/DazRave%20Cascade/icons/security-home.png
        #attachment_type: >
        #  default


# Triggering

- alias: 'Alarm reminder (home)'
  trigger:
    - platform: state
      entity_id: binary_sensor.landing
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_home'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.all_speakers
      volume_level: 0.5
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.all_speakers
      volume_level: 1.0

- alias: 'Announce detection (home/away)'
  trigger:
    - platform: state
      entity_id: group.groundfloorpir
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'armed_home'
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'armed_away'
  action:
  - service: tts.google_say
    entity_id: media_player.all_speakers
    data_template:
      message: "{{states('sensor.last_activity')}}, detected!"
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
  - service: light.turn_on
    entity_id: group.all_lights

- alias: 'Trigger Alarm'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.all_speakers
      volume_level: 1
  - service: tts.google_say
    entity_id: media_player.all_speakers
    data:
      message: "Intruder, {{states('sensor.last_activity')}}, Intruder, {{states('sensor.last_activity')}}, Intruder, {{states('sensor.last_activity')}}, Intruder, {{states('sensor.last_activity')}}, Intruder"
  - service: notify.slack
    data:
      message: "House alarm has been activated!"

# Automation setting

- alias: 'Turn on alarm when away'
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'away'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: group.internalpir
      state: 'off'
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm

- alias: 'Turn on alarm when sleeping'
  trigger:
    - platform: state
      entity_id: group.internalpir
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: group.residents
      state: 'home'
    - condition: state
      entity_id: sensor.last_activity
      state: 'landing_motion'
    #- condition: state
    #  entity_id: device_tracker.living_room_tv
    #  state: 'off'
  action:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.home_alarm

- alias: 'Turn off alarm when home'
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_away'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
