# MQTT Wireless sensor RESET
- alias: reset mobile PIR
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.wireless_sensor
    to: 'on'
    for:
      seconds: 5
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key1_off"


# MQTT Wireless sensor RESET
- alias: porch door reset
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.porch_door
    to: 'on'
    for:
      seconds: 20
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key4_off"
