# MQTT Wireless sensor RESET
- alias: reset mobile PIR
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.wireless_sensor
    to: 'on'
    for:
      seconds: 2
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key1_off"

# MQTT Wireless sensor RESET
- alias: porch door reset
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.porch_door
    to: 'on'
    for:
      seconds: 1
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key4_off"

- alias: switch 1 reset
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.switch_1
    to: 'on'
    for:
      seconds: 1
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key10_off"

- alias: switch 2 reset
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.switch_2
    to: 'on'
    for:
      seconds: 1
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key11_off"

- alias: switch 3 reset
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.switch_3
    to: 'on'
    for:
      seconds: 1
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key12_off"

- alias: switch 4 reset
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.switch_4
    to: 'on'
    for:
      seconds: 1
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key13_off"
