# MQTT Wireless sensor RESET
- alias: reset mobile PIR
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.wireless_sensor
    to: 'on'
    for:
      seconds: 5
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key1_off"

# MQTT Wireless sensor RESET
- alias: porch door reset
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.porch_door
    to: 'on'
    for:
      seconds: 3
  action:
  - service: mqtt.publish
    data:
      topic: tele/sonoffb/RESULT
      payload: "key4_off"

# Lockdown Resets
- alias: turn off partial lockdown if full lockdown is set
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_boolean.lockdown_full
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lockdown_partial
      state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.lockdown_partial

- alias: turn off full lockdown if partial lockdown is set
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_boolean.lockdown_partial
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lockdown_full
      state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.lockdown_full

- alias: turn off any lockdown if alarm is set
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_home'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.lockdown_full
      state: 'on'
    - condition: state
      entity_id: input_boolean.lockdown_partial
      state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.lockdown_full
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.lockdown_partial
