# Turn on before sunset
- alias: Turn on after sunset
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: light.turn_on
      entity_id: light.living_room_lamp
    - service: light.turn_on
      entity_id: light.kitchen_counter

# Turn off at sunrise
- alias: Turn off at sunrise
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunrise
      offset: "+01:00:00"
  action:
    - service: light.turn_off
      entity_id: group.all_lights
