- alias: Auto turn off all xmas lights (weekday)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.groundfloorpir
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '22:30:00'
      before: '06:00:00'
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_xmas_lights

- alias: Auto turn off all xmas lights (weekend)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.groundfloorpir
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '00:00:00'
      before: '08:00:00'
      weekday:
        - fri
        - sat
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_xmas_lights

- alias: Xmas turn off timer
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.groundfloorpir
      to: 'off'
      for:
        minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_xmas_lights
        state: 'on'
      - condition: time
        after: '13:00:00'
        before: '00:00:00'
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_xmas_lights

- alias: Motion triggered xmas lights
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.internalpir
    to: 'on'
  condition:
    - condition: state
      entity_id: group.xmas_tree_lights
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.xmas_tree_lights
