- alias: 'Auto turn on all xmas lights before sunset'
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: light.turn_on
      entity_id: group.all_xmas_lights

- alias: 'Motion triggered xmas tree lights'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room
      to: 'on'
  condition:
    - condition: state
      entity_id: group.xmas_tree_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.xmas_tree_lights

- alias: 'Auto turn off all xmas lights'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '00:00:00'
  action:
  - service: switch.turn_off
    entity_id: group.all_xmas_lights

- alias: Xmas tree timer
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.groundfloorpir
      to: 'off'
      for:
        minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.xmas_tree_lights
        state: 'on'
      - condition: time
        after: '13:00:00'
        before: '00:00:00'
  action:
  - service: light.turn_off
    entity_id: group.xmas_tree_lights
