#- platform: pi_hole
#  monitored_conditions:
#    - ads_blocked_today
#    - ads_percentage_today
#    - unique_domains
#    - dns_queries_today

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: disk_free
      arg: /home
    - type: last_boot

- platform: cpuspeed

- platform: yr

- platform: google_wifi
  host: 192.168.0.1
  name: Cascade Network

- platform: season
  type: astronomical

- platform: metoffice
  api_key: !secret met_office_api_key
  monitored_conditions:
    - weather
    - temperature
    - feels_like_temperature
    - wind_speed
    - wind_direction
    - wind_gust
    - visibility
    - visibility_distance
    - uv
    - precipitation
    - humidity

- platform: lastfm
  api_key: !secret lastfm_api_key
  users:
    - dazrave

- platform: steam_online
  api_key: !secret steam_api
  accounts:
    - 76561198131186539

#- platform: haveibeenpwned
#  email:
#    - !secret darren_email

#- platform: google_travel_time
#  name: Darren time to Home
#  api_key: !secret google_maps_api_key
#  origin: device_tracker.google_maps_109369459484370838012 # Darren
#  destination: zone.home

#- platform: google_travel_time
#  name: Stephanie time to Home
#  api_key: !secret google_maps_api_key
#  origin: device_tracker.google_maps_112615938731075593608 # Stephanie
#  destination: zone.home

- platform: template
  sensors:
    last_activity:
      friendly_name: 'Last Activity'
      value_template: >
        {%- set sensors = [states.input_boolean.garage_door, states.binary_sensor.kitchen, states.binary_sensor.wireless_sensor, states.binary_sensor.landing, states.binary_sensor.living_room, states.binary_sensor.porch_door] %}
        {% for sensor in sensors %}
          {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
            {{ sensor.name }}
          {% endif %}
        {% endfor %}

#- platform: speedtest
#  minute: 30
  #hour:
  #  - 0
  #  - 6
  #  - 12
  #  - 18
  #server_id: 3448
#  monitored_conditions:
#    - ping
#    - upload
#    - download

- platform: whois
  domain: cascadehome.net


#- platform: uk_transport
#  app_id: 292ac24b
#  app_key: 14efd2cfeaee4ec51213aba19a54692c
#  queries:
#    - mode: bus
#      origin: 1800NB05021 # TickX (Depart)
#      destination: WAT


# 1800NB03521 (Arrive)